### ISSUE TITLE
To Whomever is the ScrumMaster (because I don't know who is)

### ISSUE THREAD

**Issue by TarahAndre** [AmableAAristy/bookstore-api#13]
**I sent the following message on WhatsApp recently but I don't know if anybody had seen it, so I'm posting it here today:**
I'm addressing this message to whomever is the scrum master (or ScrumMaster [because I don't know who is]), since I am not able to edit these documents that you're editing, I am sending my stories: 
Principal story
1. As an administrator I want to create a book with its ISBN, name, description, price, author, genre, publisher, publication year and number of copies sold so that I can retrieve the details of the book in the system after I create them.

Last week's stories:
1. I use stickies to write stories for the details of a book.
2. I created a flowchart on Lucidchart for the details of a book.
3. I started to design and adding data to my database.
4. I started coding in my branch and I coded for many days (I created that branch)

This week's stories:
1. I finished designing and adding data to my database.
2. I started working on my UML diagrams, so I made a use case diagram.
3. I continued coding on my branch (Not yet functional)

I also posted an issue on GitHub that has the Use Case diagram.

**Comment by barmstrong1188** [comment]
Thank you! I will use this for your part in our deliverables. 

And for future reference, we vote on the roles every sprint. You can always refer back to that in our WhatsApp if needed! 

![sprint2roles](https://github.com/AmableAAristy/bookstore-api/assets/65680645/9840a29e-244a-4d40-af6a-dcba6865ba10)

**Comment by barmstrong1188** [comment]
Also, at any point in time you can click on messages you've sent in WhatsApp and it will literally tell you who has read it.

![Screenshot 2024-02-18 172746](https://github.com/AmableAAristy/bookstore-api/assets/65680645/bff8b60b-e1b1-4e98-a5ea-1496e9f4a66a)
